# set the target executables that need to be built
TARGETS := ExpressBetaDiversity

# set some flags and compiler/linker specific commands
CXXFLAGS = -O2 -fpermissive
LDFLAGS = -Wall

include generic.mk